seed: 77
use_wandb: True
wandb_project: signate_hiroshima_test
water_csv_path: data/timeseries/water.csv

n_folds: 3
use_folds: [0, 1, 2]

device: cuda
input_size: 1
hidden_size: 128
output_size: 1
input_sequence_size: 30
output_sequence_size: 24
train_bs: 128
valid_bs: 128
n_workers: 2
n_epochs: 10
lr: 1e-2
weight_decay: 1e-6